version: "3.7"

services:
  bth-frontend:
    image: bth-frontend
    build: .
    container_name: bth-frontend
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    tty: true
